### ISSUE TITLE
Add missing LICENSE file & question related to repo on pub.dev

### ISSUE THREAD

**Issue by BrutalCoding** [harrisonvanderbyl/rwkv-dart#1]
Hey, 

I was looking around for Flutter/Dart projects that are tinkering with ML/AI stuff and found this repo. Keep it up!

Is this pub.dev package owned by you?: https://pub.dev/packages/tokenizerx
There's no repo linked on that page and neither the author is stated.

Did you manage to inference with an rwkv model through Dart?

**Comment by harrisonvanderbyl** [comment]
I do not own that package, but it was very useful.

I was able to do inference with this project,
the file converter is over at my rwkv-cpp-accelerated project

**Comment by BrutalCoding** [comment]
Thanks for replying quickly.

I also just noticed you added a license https://github.com/harrisonvanderbyl/rwkv-dart/commit/80d13d8dcff3fb9f11b9134781de34df9fac8358 thus this issue is resolved 👍
